server:
  port: 8766

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://msk-eureka:8761/eureka

spring:
  application:
    name: msk-boot-admin
  boot:
    admin:
      context-path: /admin