server:
  port: 8888

eureka:
  client:
    service-url:
      # 注册服务到eureka上，记住这里要加上 eureka-server 的用户名和密码
      defaultZone: http://eureka1:8761/eureka

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/
          # label: master # 配置仓库的分支
          # git:
          # uri: http://twtpebuildsv.deltaww.com/ams/cloud/roma-config
          # searchPaths: '{application}'
          # username: Anjin.Ma
          # password: Delta87654