server:
  port: 8784
  servlet:
    context-path: /order/api

eureka:
  instance:
    # 强制使用IP地址进行注册
    prefer-ip-address: true
    # 设置客户端实例id, 若使用IP地址注册，这个配置必须有，否则会显示成 localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      # 注册服务到eureka上
      defaultZone: http://msk-eureka:8761/eureka

spring:
  application:
    name: msk-order
  zipkin:
    base-url: http://localhost:9411

security:
  oauth2:
    resource:
      id: msk-order
      user-info-uri: http://msk-auth/auth/api/user/current
      prefer-token-info: false
      loadBalanced: true

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3500

logging:
  level:
    com.delta.roma: INFO
    com.netflix.loadbalancer: INFO
    org.springframework.security: DEBUG