server:
  port: 8781

eureka:
  client:
    service-url:
      # 注册服务到eureka上，记住这里要加上 eureka-server 的用户名和密码
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: config-server
  profiles:
    active: native
  boot:
    admin:
      client:
        url: http://admin-server:8800/admin