server:
  port: 8765

eureka:
  client:
    service-url:
      # 注册服务到eureka上，记住这里要加上eureka-server的用户名和密码
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: msk-gateway
  profiles:
    active: native
  cloud:
    config:
      uri: http://config-server:8888
      name: application-zuul
      profile: pro
      # label:
  boot:
    admin:
      client:
        url: http://admin-server:8800/admin

zuul:
  routes:
    admin-server:
      sensitiveHeaders: "*"
      path: /admin/**
      service-id: admin-server
      stripPrefix: false
    msk-auth:
      sensitiveHeaders: "*"
      path: /auth
      service-id: msk-auth
      stripPrefix: false
    msk-consumer:
      sensitiveHeaders: "*"
      path: /consumer
      service-id: msk-consumer
      stripPrefix: false

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /actuator
      cors:
        allowed-origins: true
      exposure:
        include:
          - '*'

logging:
  level:
    com.delta.roma.gateway: INFO